# Yarn 4 Configuration for 2025
nodeLinker: node-modules
enableGlobalCache: true
compressionLevel: 0
enableTelemetry: false

# Performance optimizations
httpTimeout: 60000

# Package extensions for compatibility
packageExtensions:
  "@modelcontextprotocol/sdk@*":
    dependencies:
      "@types/node": "*"
