compressionLevel: 0

enableGlobalCache: true

enableTelemetry: false

httpProxy: "http://webproxy.ext.ti.com:80"

httpTimeout: 60000

httpsProxy: "http://webproxy.ext.ti.com:80"

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@modelcontextprotocol/sdk@*":
    dependencies:
      "@types/node": "*"
